name : server-deploy

on: 
  push: 
    branches : ["server-main"]

env:
 AWS_REGION : ap-northeast-2
 DOCKER_USERNAME : ${{secrets.DOCKER_USERNAME}}
 DOCKER_PASSWORD : ${{secrets.DOCKER_PASSWORD}}
 DOCKER_IMAGE : ${{secrets.DOCKER_IMAGE}}

jobs:
  ci:
    name : ci (before jenkins use)
    runs-on : ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name : Checkout
        uses : actions/checkout@v2

      - name : Set up node.js
        uses : actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json

      - name : Docker Build image
        env : 
          DATABASE : ${{ secrets.DATABASE }}
          AWS_LAMBDA_URL : ${{ secrets.AWS_LAMBDA_URL }}
          NEO4J_URI : ${{ secrets.NEO4J_URI }}
          NEO4J_USER : ${{ secrets.NEO4J_USER }}
          NEO4J_PASSWORD : ${{ secrets.NEO4J_PASSWORD }}
          VITE_APP_GITHUB_CLIENT_ID : ${{ secrets.VITE_APP_GITHUB_CLIENT_ID }}
          VITE_APP_GITHUB_CLIENT_SECRET : ${{ secrets.VITE_APP_GITHUB_CLIENT_SECRET }}
        run : | 
          cd server
          echo "DATABASE=$DATABASE" >> .env
          echo "AWS_LAMBDA_URL=$AWS_LAMBDA_URL" >> .env
          echo "NEO4J_URI=$NEO4J_URI" >> .env
          echo "NEO4J_USER=$NEO4J_USER" >> .env
          echo "NEO4J_PASSWORD=$NEO4J_PASSWORD" >> .env
          echo "VITE_APP_GITHUB_CLIENT_ID=$VITE_APP_GITHUB_CLIENT_ID" >> .env
          echo "VITE_APP_GITHUB_CLIENT_SECRET=$VITE_APP_GITHUB_CLIENT_SECRET" >> .env
          echo "FRONT_URL=$FRONT_URL" >> .env
          echo "IMG_S3_BUCKET_NAME=$IMG_S3_BUCKET_NAME" >> .env
          echo "AWS_ACCESS_KEY=$AWS_ACCESS_KEY" >> .env
          echo "AWS_SECRET_KEY=$AWS_SECRET_KEY" >> .env
          docker build -t ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE}} . 
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Publish to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{secrets.DOCKER_IMAGE}}
  
      - name : Ec2 Docker Run
        uses : appleboy/ssh-action@v0.1.10
        with:
          HOST : ${{ secrets.EC2_HOST }}
          USERNAME : ${{ secrets.EC2_USERNAME }}
          KEY : ${{ secrets.EC2_KEY}}
          PORT : 22
          DATABASE : ${{ secrets.DATABASE }}
          AWS_LAMBDA_URL : ${{ secrets.AWS_LAMBDA_URL }}
          NEO4J_URI : ${{ secrets.NEO4J_URI }}
          NEO4J_USER : ${{ secrets.NEO4J_USER }}
          NEO4J_PASSWORD : ${{ secrets.NEO4J_PASSWORD }}
          script : |
            sudo docker kill ${{secrets.DOCKER_IMAGE}}
            sudo docker rm -f ${{secrets.DOCKER_IMAGE}}
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE }}

            export NODE_OPTIONS=--max_old_space_size=7000
            sudo docker run -d -p 4000:4000 --name ${{secrets.DOCKER_IMAGE}} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE }}
               
      # - name : Set up Docker buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

