name : server-deploy

on : 
  push: ["server-main"]
  paths:
    - "server/**"

env:
 AWS_REGION : ap-northeast-2
 DOCKER_USERNAME : ${{secret.DOCKER_USERNAME}}
 DOCKER_PASSWORD : ${{secret.DOCKER_PASSWORD}}
 DOCKER_IMAGE : ${{secret.DOCKER_IMAGE}}

jobs:
  ci:
    name : ci (before jenkins use)
    runs-on : ubuntu-20.04
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name : Checkout
        uses : actions/checkout@v2

      - name : Set up node.js
        uses : actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name : Set up Env variables
        env : 
          DATABASE : ${{ secrets.DATABASE }}
          AWS_LAMBDA_URL : ${{ secrets.AWS_LAMBDA_URL }}
          NEO4J_URI : ${{ secrets.NEO4J_URI }}
          NEO4J_USER : ${{ secrets.NEO4J_USER }}
          NEO4J_PASSWORD : ${{ secrets.NEO4J_PASSWORD }}
        run: |
          cd server
          echo "DATABASE=$DATABASE" > .env
          echo "AWS_LAMBDA_URL=$AWS_LAMBDA_URL" > .env
          echo "NEO4J_URI=$NEO4J_URI" > .env
          echo "NEO4J_USER=$NEO4J_USER" > .env
          echo "NEO4J_PASSWORD=$NEO4J_PASSWORD" > .env

      - name : Docker Build image
        run : | 
          cd server
          docker build -t ${{env.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE}} . 
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Publish to docker hub
        run: docker push ${{ env.DOCKERHUB_USERNAME }}/${{env.DOCKER_IMAGE}}
  
      - name : Ec2 Docker Run
        uses : appleboy/ssh-action@master
        wiht:
          host : ${{ secrets.EC2_HOST }}
          username : ${{ secrets.EC2_USERNAME }}
          EC2_KEY : ${{ secrets.EC2_KEY}}
          DATABASE : ${{ secrets.DATABASE }}
          AWS_LAMBDA_URL : ${{ secrets.AWS_LAMBDA_URL }}
          NEO4J_URI : ${{ secrets.NEO4J_URI }}
          NEO4J_USER : ${{ secrets.NEO4J_USER }}
          NEO4J_PASSWORD : ${{ secrets.NEO4J_PASSWORD }}
          script : |
            sudo docker kill ${{env.DOCKER_IMAGE}}
            sudo docker rm -f ${{env.DOCKER_IMAGE}}
            sudo docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}

            export NODE_OPTIONS=--max_old_space_size=7000
            sudo docker run -p 4000:4000 \
              --name ${{env.DOCKER_IMAGE}} \
              - d ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE }}
      # - name : Set up Docker buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

